### ISSUE TITLE
default write is scary

### ISSUE THREAD

**Issue by dkj** [whitwham/tears#3]
Suggest
- adding a `-w` option for when writing at file to iRODS
- retain current behaviour (of writing without `-w`, but allowing `-w` option on command line) for next revision
- drop writing without the `-w` option for following revision

**Comment by whitwham** [comment]
Good idea.  Not having an option comes from the origin of tears being a write only program.  First part is done.  I will leave this issue open until the -w becomes mandatory for writing.
