### ISSUE TITLE
support `tears -r -R src-resource /path` ?

### ISSUE THREAD

**Issue by mcast** [whitwham/tears#6]
We are considering using `tears -r` to feed a bandwidth-throttled `ichksum -K` substitute, with additional benefit of ongoing end-to-end transfer verification.

If we went ahead with that, we would want to specify the source resource rather than let tears choose, so we can verify every copy.  How big does that look?

We don't need `tears -w -R foo ...`.

@kript FYI

**Comment by whitwham** [comment]
Can you not do this by using the URI method mentioned in the Readme? e.g.

tears -r irods://irods-example-host/seq/file.bam > out.bam

Though I may be misinterpreting what resource you are talking about.

**Comment by mcast** [comment]
On Wed, Nov 23, 2016 at 06:04:07AM -0800, Andrew Whitwham wrote:

> Can you not do this by using the URI method mentioned in the Readme? e.g.
> 
> tears -r irods://irods-example-host/seq/file.bam > out.bam

Yes, sorry for not RingTFM.  Except it doesn't work...

Trying the /software/solexa/pkg/tears/current/tears I think it is too old.

Trying with a resource name, I get `hostname: [irods-cgp-sr06-bc] h_errno [1] hstrerror [Unknown host]` so that's clear enough.
We wouldn't expect to store a replica on two partitions of one host,
so the host vs. resource distinction is probably not important at this
point.

Trying with v1.2.1 and a short hostname, it tries to connect on port 0

  mca@cgpbar:~$ i-cgp /software/solexa/pkg/tears/04.10.16-v4/tears -d -v -b 16384 -r irods://irods-cgp-sr06/cgp/CANT/ireg-tmp/id_p_u=11/4474.bam | delayblock > /dev/null 
  Setting client name to: tears:1.2.1
  File name is /cgp/CANT/ireg-tmp/id_p_u=11/4474.bam
  host irods-cgp-sr06
  zone 
  user 
  port 0
  ERROR: _rcConnect: connectToRhost error, server on irods-cgp-sr06:0 is probably down status = -305111 USER_SOCK_CONNECT_ERR, Connection refused
  Error: rcConnect failed: name USER_SOCK_CONNECT_ERR (Connection refused) (-305111) _rcConnect: connectToRhost failed

## 

Matthew

## 

 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by mcast** [comment]
On Wed, Nov 23, 2016 at 06:40:10AM -0800, Matthew Astley wrote:

> Trying with v1.2.1 and a short hostname, it tries to connect on port 0
> 
>   mca@cgpbar:~$ i-cgp /software/solexa/pkg/tears/04.10.16-v4/tears -d -v -b 16384 -r irods://irods-cgp-sr06/cgp/CANT/ireg-tmp/id_p_u=11/4474.bam | delayblock > /dev/null 
>   Setting client name to: tears:1.2.1
>   File name is /cgp/CANT/ireg-tmp/id_p_u=11/4474.bam
>   host irods-cgp-sr06
>   zone 
>   user 
>   port 0
>   ERROR: _rcConnect: connectToRhost error, server on irods-cgp-sr06:0 is probably down status = -305111 USER_SOCK_CONNECT_ERR, Connection refused
>   Error: rcConnect failed: name USER_SOCK_CONNECT_ERR (Connection refused) (-305111) _rcConnect: connectToRhost failed

and the config isn't completely wrong,

  mca@cgpbar:~$ i-cgp sh -c 'grep -Hi port $irodsEnvFile'
  /nfs/users/nfs_m/mca/.irods/irodsenv-cgp:# export irodsEnvFile=~/.irods/irodsenv-cgp  FuseCacheDir=/tmp/mca.fuseCache.cgp
  /nfs/users/nfs_m/mca/.irods/irodsenv-cgp:# NOTICE: irodsPort=1247
  /nfs/users/nfs_m/mca/.irods/irodsenv-cgp:irodsPort=1247

## 

Matthew

## 

 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by whitwham** [comment]
Which version of iRODS are you using?  Version v4.1.8+ uses IRODS_ENVIRONMENT_FILE rather than  irodsEnvFile.

Also, while the direct resource request works for reading on iRODS v3, I have no way of testing it on v4 (the upgrade broke some of my logins and they have yet to be restored).

**Comment by mcast** [comment]
On Wed, Nov 23, 2016 at 06:55:52AM -0800, Andrew Whitwham wrote:

> Which version of iRODS are you using?

3.3.1

> Version v4.1.8+ uses IRODS_ENVIRONMENT_FILE rather than  irodsEnvFile.

I know thanks, and my i-cgp wrapper also knows (so far as it can tell
which you need).

> Also, while the direct resource request works for reading on iRODS
> v3, I have no way of testing it on v4 (the upgrade broke some of my
> logins and they have yet to be restored).

We don't have a 4.1.x timeline yet.

## 

Matthew

## 

 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by whitwham** [comment]
> and the config isn't completely wrong,

When I try using your command line (without i-cgp) I get the config fully filled out.
```
/software/solexa/pkg/tears/04.10.16-v4/tears -d -v -b 16384 -r irods://irods-cgp-sr06/cgp/CANT/ireg-tmp/id_p_u=11/4474.bam
Setting client name to: tears:1.2.1
File name is /cgp/CANT/ireg-tmp/id_p_u=11/4474.bam
host irods-cgp-sr06
zone Sanger1
user aw7
port 1247
```
Which makes it look like an environment problem.  This is an internal work issue and I do not really want to pursue it on a public forum.  You know my email address and your office is just the other side of the oak tree if you want to walk over and see me.
